# frozen_string_literal: true

ruby "2.7.0"

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

group :test, :development do
  gem "standard", "~> 0.1.7"
end

group :test do
  gem "apparition", "~> 0.4.0"
  gem "capybara", "~> 3.29"
  gem "rspec", "~> 3.9"
end
