require "bundler/setup"
require "rake"
require "rake/tasklib"
require_relative "./app"

require "jacks/tasks/asset_tasks"
Jacks::Tasks::AssetTasks.generate_all

require "jacks/tasks/deploy_tasks"
Jacks::Tasks::DeployTasks.generate_all

require "jacks/tasks/db_tasks"
Jacks::Tasks::DbTasks.generate_all
